"""Implementation/testbed evaluation pattern labels — not normative ABIS Outcome terms."""

from __future__ import annotations

PATTERN_EXACT_MATCH = "EXACT_MATCH"
PATTERN_NO_AVAILABILITY = "NO_AVAILABILITY"
PATTERN_CONSTRAINT_MISMATCH = "CONSTRAINT_MISMATCH"
PATTERN_BUSINESS_REJECTED = "BUSINESS_REJECTED"
PATTERN_PARTIAL_RESULT = "PARTIAL_RESULT"
PATTERN_PENDING = "PENDING"
PATTERN_TECHNICAL_ERROR = "TECHNICAL_ERROR"
PATTERN_TIMEOUT = "TIMEOUT"
PATTERN_DUPLICATE_IDEMPOTENT = "DUPLICATE_IDEMPOTENT"
PATTERN_TECHNICAL_SUCCESS_BUSINESS_MISMATCH = "TECHNICAL_SUCCESS_BUSINESS_MISMATCH"

ALL_PATTERNS = (
    PATTERN_EXACT_MATCH,
    PATTERN_NO_AVAILABILITY,
    PATTERN_CONSTRAINT_MISMATCH,
    PATTERN_BUSINESS_REJECTED,
    PATTERN_PARTIAL_RESULT,
    PATTERN_PENDING,
    PATTERN_TECHNICAL_ERROR,
    PATTERN_TIMEOUT,
    PATTERN_DUPLICATE_IDEMPOTENT,
    PATTERN_TECHNICAL_SUCCESS_BUSINESS_MISMATCH,
)

EVALUATION_MATCH = "MATCH"
EVALUATION_MISMATCH = "MISMATCH"

SEMANTIC_AUTHORITY = "NONE"
