"""TEST-ONLY scenario catalog for Controlled Reservation Simulator.

Scenarios are selected via request field `test_scenario` OR header
`X-CRS-Test-Scenario`. Production-facing callers must omit both.
"""

from __future__ import annotations

from typing import Optional

# TEST ONLY — not part of any normative ABIS API.
SCENARIO_NORMAL_SUCCESS = "NORMAL_SUCCESS"
SCENARIO_NO_AVAILABILITY = "NO_AVAILABILITY"
SCENARIO_CONSTRAINT_MISMATCH = "CONSTRAINT_MISMATCH"
SCENARIO_BUSINESS_REJECTED = "BUSINESS_REJECTED"
SCENARIO_PARTIAL_RESULT = "PARTIAL_RESULT"
SCENARIO_PENDING = "PENDING"
SCENARIO_TECHNICAL_ERROR = "TECHNICAL_ERROR"
SCENARIO_TIMEOUT = "TIMEOUT"
SCENARIO_DUPLICATE_IDEMPOTENT = "DUPLICATE_IDEMPOTENT"
SCENARIO_TECHNICAL_SUCCESS_BUSINESS_MISMATCH = "TECHNICAL_SUCCESS_BUSINESS_MISMATCH"
SCENARIO_TECHNICAL_SUCCESS_TIME_MISMATCH = "TECHNICAL_SUCCESS_TIME_MISMATCH"
SCENARIO_TECHNICAL_SUCCESS_SEATING_MISMATCH = "TECHNICAL_SUCCESS_SEATING_MISMATCH"

ALL_SCENARIOS = (
    SCENARIO_NORMAL_SUCCESS,
    SCENARIO_NO_AVAILABILITY,
    SCENARIO_CONSTRAINT_MISMATCH,
    SCENARIO_BUSINESS_REJECTED,
    SCENARIO_PARTIAL_RESULT,
    SCENARIO_PENDING,
    SCENARIO_TECHNICAL_ERROR,
    SCENARIO_TIMEOUT,
    SCENARIO_DUPLICATE_IDEMPOTENT,
    SCENARIO_TECHNICAL_SUCCESS_BUSINESS_MISMATCH,
    SCENARIO_TECHNICAL_SUCCESS_TIME_MISMATCH,
    SCENARIO_TECHNICAL_SUCCESS_SEATING_MISMATCH,
)


def normalize_scenario(value: Optional[str]) -> Optional[str]:
    if value is None:
        return None
    s = str(value).strip().upper()
    if not s:
        return None
    if s not in ALL_SCENARIOS:
        return s  # unknown — engine reports Native Result error
    return s
